[package]
name = "rust-method-count"
version = "0.1.0"
authors = ["gibix <gibix@riseup.net>"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"]}
structopt = "0.3"
log = "0.4"
pretty_env_logger = "0.3"
